title: giardino punk
description: Mi chiamo Stefano e questo è il mio giardino digitale.
image: imgs/img0.jpg
author:
  name: Stefano Zuliani
  twitter: ZulianiStph
twitter:
  username: ZulianiStph
  card: summary
social:
  name: Stefano Zuliani
  links:
    - https://twitter.com/ZulianiStph
    - https://www.linkedin.com/in/s-zuliani/
# All the plugins we will be installing now that we won't be using GitHub Pages
plugins:
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
  - jekyll-seo-tag
# The default Jekyll theme we will be using
theme: jekyll-theme-primer
# The GitHub repository that we are hosting our foam workspace from [default is user/repo]
repository: crixer18/giadino-punk
# Generate permalinks in format specified in: https://jekyllrb.com/docs/permalinks/#built-in-formats
permalink: pretty